apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240204042802.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240204042802.0.0+build.6aff574
  releaseNotes: |
    Release v20240204042802.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-04-02-2024-00-39-11-236541315/where-for-dinner-my-apps-bundle@sha256:f264bb2aaf95635fc72517f147e5ea5e8698089c8836ea9592ea9e9e0249cf7c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

